### PR TITLE
chore: skip job on gh-pages branch

### PR DESCRIPTION
**Pull request by richardcase**
Signed-off-by: Richard Case <198425+richardcase@users.noreply.github.com>

```release-note
NONE
```

### CODE REVIEW

**Comment by kubecoins-kryten** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **richardcase** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @richardcase` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubecoins%2Ftest-infra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/kubecoins/test-infra/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by multipleinheritance** [comment]
\lgtm

**Comment by kubecoins-kryten** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/kubecoins/test-infra/pull/20#issuecomment-783383386" title="LGTM">multipleinheritance</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubecoins%2Ftest-infra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/kubecoins/test-infra/blob/main/OWNERS)~~ [multipleinheritance]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by kubecoins-kryten** [comment]
LGTM label has been added.  <details>Git tree hash: b18bb69b4c49cb44a2087f4307eadf27aee35661</details>

**Pull request merged**
